bindings:
  - output: ../../libs/generated/src/backend.ts
    profile: !ClassValidator
      class_name: ApplicationConfig
  - output: ../../libs/generated/src/backend.py
    profile: !Pydantic {}

config:
  - !IncludePartial mail
  - !IncludePartial api
